services:
  db:
    image: postgres:15-alpine
    container_name: sport-events-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: sports_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sport-events-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sport-events-backend
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: secret
      DATABASE_HOST: db
      DATABASE_PORT: "5432"
      DATABASE_NAME: sports_db
      DJANGO_SETTINGS_MODULE: sport_events.settings
    ports:
      - "8000:8000"
    networks:
      - sport-events-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sport-events-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - sport-events-network

networks:
  sport-events-network:
    driver: bridge

volumes:
  pgdata:
