services:
  db:
    image: postgres:15-alpine
    container_name: sport-events-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: sports_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sports_db"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - sport-events-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sport-events-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_USER: postgres
      DATABASE_PASSWORD: secret
      DATABASE_HOST: db
      DATABASE_PORT: "5432"
      DATABASE_NAME: sports_db
      DJANGO_SETTINGS_MODULE: sport_events.settings
    ports:
      - "8000:8000"
    networks:
      - sport-events-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sport-events-frontend
    ports:
      - "3000:80"
    networks:
      - sport-events-network

networks:
  sport-events-network:
    driver: bridge

volumes:
  pgdata:
